# *********************************
# * Parameters for metqc pipeline *
# *********************************

# List of files
list_files: "/Users/alana.schick/Desktop/dropbox_temp/bcch/projects/shotgun_optimization/list_files_shotgun.txt"
# Path to raw sequences
path: "/Users/alana.schick/Desktop/dropbox_temp/bcch/sequence_data/2021_06_18/"
# Suffix for forward reads
for: "_R1_001.fastq.gz"
# Suffix for reverse reads
rev: "_R2_001.fastq.gz"
# Run fastqc and multiqc only
qc_only: FALSE

### Cutadapt parameters
# Choose whether to run cutadapt
run_cutadapt: TRUE
# Adapters for cutadapt
fwd_adapter: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
rev_adapter: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
# Minimum length for cutadapt
minlength: 60
# Maximum number of N bases allowed
maxn: 10

### BBMap parameters
# Choose whether to run bbmap
run_bbmap: TRUE
# Path and name of reference fasta for bbmap
bbmap_ref: "/Users/alana.schick/Desktop/dropbox_temp/bcch/reference_files/hs_GRCh38.p13.fna.gz"
